name: deployment
on:
  push:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-22.05
    - name: Checkout this repository
      uses: actions/checkout@v3
    - name: Build the static site
      run: scripts/build.sh
    - name: Add CNAME
      run: echo alt.hypered.design > _site/CNAME
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
